from setuptools import setup, find_packages
import os

setup(
    name="certainty_machine",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        # Add your dependencies here, for example:
        "numpy",
        "torch>=2.5.0",
        "datasets",
        "accelerate",
        "wandb",
        "matplotlib",
        "sentencepiece",
        "scikit-learn",
        "vllm==0.7.3",
        "einops",
        "ipykernel",
        "bitsandbytes",
        "uvicorn",
        "fastapi",
        "pydantic",
        "requests",
        "easydict",
        "tiktoken",
        "anthropic",
        "openai",
        "trl",
        "transformers",
        "datasets",
        "deepspeed",
        "scipy",
        "jaxtyping",
        "google-genai",
        "pre-commit",
        "types-requests",
        "tqdm",
        "vertexai",
        "pytest",
    ],
    # author="",
    # author_email="",
    description="Scaffolding for theorem proving.",
    long_description=open("README.md").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    python_requires=">=3.10",  # Adjust minimum Python version as needed
)
